^[SingleTrackListeners]
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:   <http://example.org/owlim#>
SELECT ?user1 ?user2
WHERE {
       ?user1 ex:listens ?md1 .
       ?user2 ex:listens ?md2 .
       ?md1 ex:hasTrackId ?track .
       ?md2 ex:hasTrackId ?track .
       FILTER (?user1 != ?user2)
}
LIMIT 100
