^[SumOfListenings]
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:   <http://example.org/owlim#>
SELECT (SUM(?count) AS ?sum)
WHERE {
       ?md ex:hasListenCount ?count .
       ?md ex:hasTrackId ?track .
       ?track ex:hasAuthor "Paul van Dyk" .
}

