^[UserTracks]
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:   <http://example.org/owlim#>
SELECT DISTINCT ?user ?t1 ?t2 ?t3
WHERE {
       ex:baed1e0d6a0a4b45e84bab05f826cdc3d04ba7cb ex:listens ?t1 .
       ex:baed1e0d6a0a4b45e84bab05f826cdc3d04ba7cb ex:listens ?t2 .
       ex:baed1e0d6a0a4b45e84bab05f826cdc3d04ba7cb ex:listens ?t3 .
       ?user ex:listens ?t1 .
       ?user ex:listens ?t2 .
       ?user ex:listens ?t3 .
       FILTER (?user != ex:baed1e0d6a0a4b45e84bab05f826cdc3d04ba7cb)
       FILTER (?t1 != ?t2)
       FILTER (?t1 != ?t3)
       FILTER (?t2 != ?t3)
}
LIMIT 30