/* Generated By:JavaCC: Do not edit this line. ChordParserConstants.java */
package chordest.chord.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ChordParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NATURAL = 6;
  /** RegularExpression Id. */
  int NO_CHORD = 7;
  /** RegularExpression Id. */
  int MODIFIER = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int SLASH = 10;
  /** RegularExpression Id. */
  int INTERVAL = 11;
  /** RegularExpression Id. */
  int SHORTHAND = 12;
  /** RegularExpression Id. */
  int OPEN_BRACE_AC = 13;
  /** RegularExpression Id. */
  int OPEN_BRACE = 14;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int OMIT = 17;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int AFTER_COLON = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<NATURAL>",
    "\"N\"",
    "<MODIFIER>",
    "\":\"",
    "\"/\"",
    "<INTERVAL>",
    "<SHORTHAND>",
    "\"(\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"*\"",
  };

}
