^[UserTracks]
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:   <http://example.org/owlim#>
SELECT DISTINCT ?user
WHERE {
       <{0}> ex:listens ?t1 .
       <{0}> ex:listens ?t2 .
       ?user ex:listens ?t1 .
       ?user ex:listens ?t2 .
       FILTER (?user != <{0}>)
       FILTER (?t1 != ?t2)
}
LIMIT 10